# Generated by Django 5.0.6 on 2024-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=400)),
                ('urlToImage', models.CharField(max_length=400)),
                ('content', models.CharField(max_length=400)),
                ('publishedAt', models.DateTimeField()),
            ],
        ),
    ]
