# Generated by Django 4.2.14 on 2024-07-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('url', models.CharField(max_length=10000, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(blank=True, max_length=1000)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('urlToImage', models.CharField(blank=True, max_length=1000)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
