# Generated by Django 5.0.6 on 2024-07-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_remove_newsarticle_id_alter_newsarticle_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.CharField(default='INVALID', max_length=400, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
