# Generated by Django 5.0.6 on 2024-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_alter_newsarticle_author_alter_newsarticle_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='publishedAt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='urlToImage',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
