# Generated by Django 5.0.6 on 2024-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_alter_newsarticle_author_alter_newsarticle_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='publishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
